db_init:
  url:
    user: "simu"
    pwd: "simu123456"
    host: "localhost"
    port: 5432
    db: "simu"
  target_schema: "simu"
  cache_size: 100
  cache_ttl: 3600
  clear_exists: True

app:
  host: "127.0.0.1"
  port: 8000
